### ISSUE TITLE
Mails from eduskunta.writeinpublic.com are being sent with eduskunta.writeit.ciudadanointeligente.org links

### ISSUE THREAD

**Issue by tmtmtmtm** [ciudadanointeligente/write-it#1033]
```
Dear Anttila Sirkka-Liisa

Tõnis has sent you the following message via Eduskunta (http://eduskunta.writeit.ciudadanointeligente.org/en/)

...

your response will be published at http://eduskunta.writeit.ciudadanointeligente.org/en/thread/can-you-help-me/, 

```

**Comment by chrismytton** [comment]
This is still happening for new answer notifications, which are sent by the `handlemail` management command.

**Comment by chrismytton** [comment]
Tried to fix this by changing the contents of `/etc/exim4/virtual/i.writeinpublic.com` to the following:

```
* : |/home/writeit/handlemail_writeinpublic.sh
local_part_suffix = +* : -*
local_part_suffix_optional
```

but this given an error when the email gets piped to it, because the log file is owned by the writeit user, but the command us run by exim:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/writeit/write-it/mailit/__init__.py", line 15, in <module>
    logging.basicConfig(filename="send_mails.log", level=logging.INFO)
  File "/usr/lib/python2.7/logging/__init__.py", line 1532, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/home/writeit/write-it/send_mails.log'
```

so this certainly seems like the right approach but I need to consult with someone who is better at exim than me to figure out how to get exim to run pipe commands as a different user.

**Comment by lfalvarez** [comment]
The problem with the new answer can be solved here https://github.com/ciudadanointeligente/write-it/blob/master/nuntium/models.py#L496. But I'm slightly lost in the way in which reverse decides which site to use.

**Comment by lfalvarez** [comment]
Got it!
The thing is that it is using a ```.forward``` exim file for filtering what to do with the incoming emails, so rather than rewriting the exim config I updated the ```.forward``` file with the following.

```
# Exim filter
if $h_to matches "@writeit.ciudadanointeligente.org" then
    pipe "/home/writeit/handlemail.sh"
endif

if $h_to matches "@i.writeinpublic.com" then
    pipe "/home/writeit/handlemail_writeinpublic.sh"
endif
```

I'm not totally sure that this is the best way to close this issue, but currently does the thing. 

The problem with this solution is that if we add another site lets say *escribeenpublico.org* we would have to add another of those ifs.
