### ISSUE TITLE
Error installing django-annoying

### ISSUE THREAD

**Issue by chrismytton** [ciudadanointeligente/write-it#1076]
I get this error when running `pip install -r requirements.txt`:

```
Downloading/unpacking django-annoying (from -r requirements.txt (line 42))
  Downloading django-annoying-0.8.2.linux-x86_64.tar.gz
  Running setup.py egg_info for package django-annoying
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/home/vagrant/writeit-virtualenv/build/django-annoying/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/home/vagrant/writeit-virtualenv/build/django-annoying/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/vagrant/writeit-virtualenv/build/django-annoying
Storing complete log in /home/vagrant/.pip/pip.log
(writeit-virtualenv)vagrant@precise64:/vagrant$
```

**Comment by chrismytton** [comment]
Installing from github seems to workaround this issue:

```
pip install git+ssh://git@github.com/skorokithakis/django-annoying.git
```

**Comment by tmtmtmtm** [comment]
was this just a temporary issues, or is this something that should be fixed in `requirements.txt`?

**Comment by chrismytton** [comment]
I believe this was fixed in https://github.com/ciudadanointeligente/write-it/pull/1098.
