### ISSUE TITLE
Message not sent in Test Mode

### ISSUE THREAD

**Issue by michalskop** [ciudadanointeligente/write-it#1115]
I successfully created

http://plasy-test.writeinpublic.com/

sent a trial message, got to confirm it, but did not receive it as I should have ("All mails will be sent to you, rather than the representatives.")

The message is shown correctly on the web: 
http://plasy-test.writeinpublic.com/es/thread/test-118/

**Comment by chrismytton** [comment]
The following error is appearing in the `~writeit/logs/celery_worker_writeinpublic.log`:

```
[2016-01-08 12:30:00,021: ERROR/MainProcess] Task nuntium.tasks.send_mails_task[aeb741c2-3c69-4fa5-a5c2-e95aa6aa20ce] raised unexpected: KeyError(u'autor',)
Traceback (most recent call last):
  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/writeit/write-it/nuntium/tasks.py", line 13, in send_mails_task
    send_mails()
  File "/home/writeit/write-it/nuntium/management/commands/send_mails.py", line 14, in send_mails
    outbound_message.send()
  File "/home/writeit/write-it/nuntium/models.py", line 664, in send
    successfully_sent, fatal_error = plugin.send(self)
  File "/home/writeit/write-it/mailit/__init__.py", line 60, in send
    text_content = template.get_content_template().format(**context)
KeyError: u'autor'
```

@lfalvarez Any ideas what might be causing this?

**Comment by chrismytton** [comment]
Ok it looks like one of the templates contains `{autor}` instead of `{author}`, which is what's causing the error above, but that doesn't explain why email sending is failing for @michalskop. I've also tried it on my test instance and can reproduce the problem. After clicking the confirmation link in the email nothing else is sent.

**Comment by tmtmtmtm** [comment]
@lfalvarez Did you find out anything useful about this?

**Comment by lfalvarez** [comment]
Hey not really! but I'm just to give it a go!

**Comment by lfalvarez** [comment]
Hey I resent the message and it seems to be working.
@michalskop, I think the testing email should be in your inbox :smile:

**Comment by michalskop** [comment]
I got it now.

**Comment by michalskop** [comment]
@lfalvarez however, I tried to send a new test message and again, I have not received it.

**Comment by lfalvarez** [comment]
Testing again :smile:

**Comment by michalskop** [comment]
Came, but later.
(+ came with the previous message again)

**Comment by lfalvarez** [comment]
I know what it is. Apparently if there is a bad template it crashes in sending the rest of the messages.

**Comment by michalskop** [comment]
And is it the Czech translation?

**Comment by lfalvarez** [comment]
noup it doesn't have to do with the Czech translation.
