### ISSUE TITLE
Failing migration

### ISSUE THREAD

**Issue by duncanparkes** [ciudadanointeligente/write-it#547]
Migration 50, 

nuntium/migrations/0050_auto__chg_field_writeitinstanceconfig_email_use_tls__chg_field_writeit.py

using booleans for some config fields rather than strings, fails for me with the following traceback:

Running migrations for nuntium:
 - Migrating forwards to 0050_auto__chg_field_writeitinstanceconfig_email_use_tls__chg_field_writeit.
 > nuntium:0050_auto__chg_field_writeitinstanceconfig_email_use_tls__chg_field_writeit
FATAL ERROR - The following SQL query failed: ALTER TABLE "nuntium_writeitinstanceconfig" ALTER COLUMN "email_use_tls" TYPE boolean, ALTER COLUMN "email_use_tls" DROP NOT NULL, ALTER COLUMN "email_use_tls" DROP DEFAULT;
The error was: column "email_use_tls" cannot be cast to type boolean

Error in migration: nuntium:0050_auto__chg_field_writeitinstanceconfig_email_use_tls__chg_field_writeit
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
    migration_function()
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/duncan/projects/mysociety/write-it/nuntium/migrations/0050_auto__chg_field_writeitinstanceconfig_email_use_tls__chg_field_writeit.py", line 13, in forwards
    db.alter_column(u'nuntium_writeitinstanceconfig', 'email_use_tls', self.gf('django.db.models.fields.NullBooleanField')(null=True))
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/db/generic.py", line 47, in _cache_clear
    return func(self, table, *args, **opts)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/db/generic.py", line 535, in alter_column
    flatten(values),
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/south/db/generic.py", line 282, in execute
    cursor.execute(sql, params)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/duncan/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "email_use_tls" cannot be cast to type boolean

**Comment by duncanparkes** [comment]
What was supposed to be in these config entries when they were strings?

**Comment by lfalvarez** [comment]
It should have been an empty string or None otherwise
