### ISSUE TITLE
Intermittent test failure

### ISSUE THREAD

**Issue by duncanparkes** [ciudadanointeligente/write-it#549]
On postgres and a63d9caa010ec344604342565ab9ec307767d38b.

======================================================================
ERROR: Get the url for all answers per message brings them
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/duncan/projects/mysociety/write-it/nuntium/user_section/tests/manually_create_answers_tests.py", line 83, in test_get_all_answers_url
    self.assertIn(person.name, response.content)
  File "/usr/lib/python2.7/unittest/case.py", line 803, in assertIn
    if member not in container:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6644: ordinal not in range(128)

**Comment by duncanparkes** [comment]
Actually, this one is in code I've not committed yet, so I'm going to close it. Sorry for the hasty report - I'm trying to note all the odd intermittent things so I don't lose them.
