### ISSUE TITLE
Creating a message using API bug

### ISSUE THREAD

**Issue by lfalvarez** [ciudadanointeligente/write-it#597]
```
Traceback (most recent call last):

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/tastypie/resources.py", line 195, in wrapper
    response = callback(request, *args, **kwargs)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/tastypie/resources.py", line 426, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/tastypie/resources.py", line 458, in dispatch
    response = method(request, **kwargs)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/tastypie/resources.py", line 1320, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))

  File "/home/writeit/write-it/nuntium/api.py", line 214, in obj_create
    bundle = super(MessageResource, self).obj_create(bundle, **kwargs)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/tastypie/resources.py", line 2084, in obj_create
    return self.save(bundle)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/tastypie/resources.py", line 2230, in save
    bundle.obj.save()

  File "/home/writeit/write-it/nuntium/models.py", line 363, in save
    super(Message, self).save(*args, **kwargs)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/celery_haystack/signals.py", line 21, in enqueue_save
    return self.enqueue('update', instance, sender, **kwargs)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/celery_haystack/signals.py", line 44, in enqueue
    enqueue_task(action, instance)

  File "/home/writeit/.virtualenvs/writeit/local/lib/python2.7/site-packages/celery_haystack/utils.py", line 31, in enqueue_task
    get_update_task().delay(action, identifier)

TypeError: unbound method delay() must be called with CeleryHaystackSignalHandler instance as first argument (got str instance instead)
```
This oviously has to do with CeleryHaystack

**Comment by lfalvarez** [comment]
https://github.com/django-haystack/celery-haystack/issues/36
